apiVersion: 1

datasources:
  - name: Loki
    type: loki
    url: http://loki:3100
    orgId: 1
    jsonData:
      derivedFields:
      - datasourceUid: Zipkin
        matcherRegex: ((\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+))
        url: '$${__value.raw}'
        name: TraceID