version: "3.8"
services:
  envoy-front:
    build: "$PWD/envoy-front/"
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - "$PWD/envoy-front/etc:/etc/envoy"
      - "$PWD/promtail/log/access-envoy-front.log:/dev/stdout"
    environment:
    - SERVICE_NAME=envoy-front  
  envoy-sidecar-1:
    build: "$PWD/envoy-sidecar-1/"
    volumes:
      - "$PWD/envoy-sidecar-1/etc:/etc/envoy"
      - "$PWD/promtail/log/access-envoy-sidecar-1.log:/dev/stdout"
    environment:
    - SERVICE_NAME=envoy-sidecar-1
  envoy-sidecar-2:
    build: "$PWD/envoy-sidecar-2/"
    volumes:
      - "$PWD/envoy-sidecar-2/etc:/etc/envoy"
      - "$PWD/promtail/log/access-envoy-sidecar-2.log:/dev/stdout"
    environment:
    - SERVICE_NAME=envoy-sidecar-2  
  grafana:
    image: "grafana/grafana:7.5.5"
    user: "root"
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - "$PWD/grafana/data:/var/lib/grafana"
      - "$PWD/grafana/etc:/etc/grafana"
  loki:
    image: "grafana/loki:2.2.1"
    volumes:
      - "$PWD/loki/etc:/etc/loki"
      - "$PWD/loki/data:/loki/tmp"
  prometheus:
    image: "prom/prometheus:v2.26.0"
    user: "root"
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - "$PWD/prometheus/etc:/etc/prometheus"
      - "$PWD/prometheus/data:/prometheus"
  promtail: 
    image: "grafana/promtail:2.2.1"
    volumes:
      - "$PWD/promtail/log:/var/log"
  zipkin: 
    image: "openzipkin/zipkin:2.23"
    ports:
      - "127.0.0.1:9411:9411"
  flask-app-1:
    build: "$PWD/flask-app-1/"
  flask-app-2:
    build: "$PWD/flask-app-2/"
  blackbox:
    image: "prom/blackbox-exporter:v0.18.0"
    ports:
      - "127.0.0.1:9115:9115"
    volumes:
      - "$PWD/blackbox/etc:/etc/blackbox_exporter"



    
    
  
        
  