# Positions
positions:
  filename: /tmp/positions.yaml

# Loki Server URL
clients:
  - url: http://loki:3100

scrape_configs:
  - job_name: envoy-acces-log
    static_configs:
    - targets:
        - localhost
      labels:
        job: envoy-access-log
        __path__: /var/log/
       
