{
 "title": "Envoy Global",
 "description": "Envoy proxy monitoring Dashboard with service level templates.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq_time_bucket,namespace)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(envoy_cluster_upstream_rq_time_bucket,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DownStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Downstream RPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_rq_total[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Downstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_downstream_cx_total[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Downstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_http_downstream_rq_time_bucket[5m])) by (le, service))",
     "legendFormat": "{{service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket[5m])) by (le, service))",
     "legendFormat": "{{service}} 50% "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket[5m])) by (le, service))",
     "legendFormat": "{{service}} 99%"
    }
   ]
  },
  {
   "title": "Downstream Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "UpStream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Upstream RPS",
   "type": "timeseries",
   "description": "Displays the number of Requests per Second being performed against each Upstream.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_total{namespace=~\"$Namespace\",service=~\"$Service\"}[5m])) by (service,namespace)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream CPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_cx_total{namespace=~\"$Namespace\",service=~\"$Service\"}[5m])) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{service=~\"$Service\",namespace=~\"$Namespace\"}[5m])) by (le, service, namespace))",
     "legendFormat": "{{namespace}}/{{service}} 99%"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{service=~\"$Service\",namespace=~\"$Namespace\"}[5m])) by (le, service, namespace))",
     "legendFormat": "{{namespace}}/{{service}} 90%"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{service=~\"$Service\",namespace=~\"$Namespace\"}[5m])) by (le, service, namespace))",
     "legendFormat": "{{namespace}}/{{service}} 50% "
    }
   ]
  },
  {
   "title": "Upstream Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_upstream_cx_active{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  { "title": "UpStream x", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Upstream 2xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=~\"2\"}[5m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream 3xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=\"3\"}[5m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream 4xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=\"4\"}[5m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Upstream 5xx Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_xx{namespace=~\"$Namespace\",service=~\"$Service\",envoy_response_code_class=\"5\"}[5m])) by (namespace,service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Endpoint Percentage Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service) / avg(envoy_cluster_membership_total{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Total Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_total{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Healthy Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  },
  {
   "title": "Unhealthy Endpoints",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_cluster_membership_total{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service) - avg(envoy_cluster_membership_healthy{namespace=~\"$Namespace\",service=~\"$Service\"}) by (namespace, service)",
     "legendFormat": "{{namespace}}/{{service}}"
    }
   ]
  }
 ]
}