{
 "title": "SLO",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Target SLO > 99%",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(book_store_service_error + book_store_service_latency + book_store_service_traffic ) / 3",
     "legendFormat": "participants-service"
    }
   ]
  },
  {
   "title": "Target SLO > 99%",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(book_store_service_error + book_store_service_latency + book_store_service_traffic) / 3",
     "legendFormat": "Book Store"
    }
   ]
  },
  { "title": "SLIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Error = 5xx",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "book_store_service_error", "legendFormat": "Availability" }
   ]
  },
  {
   "title": "Error  = 5xx",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "book_store_service_error", "legendFormat": "availability" }
   ]
  },
  {
   "title": "Latency < 60ms ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "book_store_service_latency", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Latency < 400ms ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "book_store_service_latency", "legendFormat": "Latency" }
   ]
  },
  {
   "title": "Traffic < 0.300 RPS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "book_store_service_traffic", "legendFormat": "Traffic" }
   ]
  },
  {
   "title": "Traffic < 0.300 RPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "book_store_service_traffic", "legendFormat": "Traffic" }
   ]
  }
 ]
}