groups:
  - name: SLI
    rules:
      - record: book_store_service_availability
        expr: |
          sum(
            count_over_time(
              envoy_cluster_upstream_rq_xx{instance="envoy-front", envoy_cluster_name="envoy-sidecar-1", envoy_response_code_class!="5"}[28d:]
            )
          )
          / 
          sum(
            count_over_time(
              envoy_cluster_upstream_rq_xx{instance="envoy-front", envoy_cluster_name="envoy-sidecar-1"}[28d:]
            )
            OR on() vector(0)
          )
          * 100 

      - record: book_store_service_latency_p99_fullfilled
        expr: | 
              histogram_quantile(
                0.99, envoy_cluster_upstream_rq_time_bucket{instance="envoy-front", envoy_cluster_name="envoy-sidecar-1", envoy_response_code_class!="5"} 
              ) < 60 
      - record: book_store_service_latency_p99_all
        expr: | 
              histogram_quantile(
                0.99, envoy_cluster_upstream_rq_time_bucket{instance="envoy-front", envoy_cluster_name="envoy-sidecar-1", envoy_response_code_class!="5"} 
              )

      - record: book_store_service_latency
        expr: |
          sum(
            count_over_time(
                book_store_service_latency_p99_fullfilled
              [28d:]
            )
          )
          /
          sum(
            count_over_time(
                book_store_service_latency_p99_all
              [28d:]
            )
            OR on() vector(0)
          )
          * 100






          